spring.application.name=backend

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:register_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASS:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8001